apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    app: gateway-service
spec:
  selector:
    app: gateway-app
  type: LoadBalancer
  externalIPs:
    - 192.168.0.10
  ports:
    - port: 80
      targetPort: 9000
      nodePort: 31000
      protocol: TCP
