apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    app: gateway-service
spec:
  selector:
    app: gateway-app
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 9000
      protocol: TCP
