apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka
spec:
  selector:
    matchLabels:
      app: eureka
  serviceName: eureka
  replicas: 2
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: amirdoc/registry-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
          env:
            - name: EUREKA_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: ereka_service_address
                  name: eureka-cm
